[2022-12-20T00:19:31.858+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tweet_etl.transform_load manual__2022-12-19T23:19:27.140340+00:00 [queued]>
[2022-12-20T00:19:31.865+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tweet_etl.transform_load manual__2022-12-19T23:19:27.140340+00:00 [queued]>
[2022-12-20T00:19:31.865+0100] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T00:19:31.865+0100] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-20T00:19:31.865+0100] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T00:19:31.877+0100] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): transform_load> on 2022-12-19 23:19:27.140340+00:00
[2022-12-20T00:19:31.881+0100] {standard_task_runner.py:55} INFO - Started process 16014 to run task
[2022-12-20T00:19:31.886+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'tweet_etl', 'transform_load', 'manual__2022-12-19T23:19:27.140340+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp5i5xz510']
[2022-12-20T00:19:31.887+0100] {standard_task_runner.py:83} INFO - Job 8: Subtask transform_load
[2022-12-20T00:19:31.933+0100] {task_command.py:389} INFO - Running <TaskInstance: tweet_etl.transform_load manual__2022-12-19T23:19:27.140340+00:00 [running]> on host kamlesh-pc
[2022-12-20T00:19:31.971+0100] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tweet_etl
AIRFLOW_CTX_TASK_ID=transform_load
AIRFLOW_CTX_EXECUTION_DATE=2022-12-19T23:19:27.140340+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-19T23:19:27.140340+00:00
[2022-12-20T00:19:31.971+0100] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kamlesh/pyenvs/data-engg/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/kamlesh/pyenvs/data-engg/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kamlesh/pyenvs/data-engg/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kamlesh/airflow/dags/demo.py", line 98, in transform_load
    from helper import sentiment_classifier
ModuleNotFoundError: No module named 'helper'
[2022-12-20T00:19:31.973+0100] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=tweet_etl, task_id=transform_load, execution_date=20221219T231927, start_date=20221219T231931, end_date=20221219T231931
[2022-12-20T00:19:31.982+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 8 for task transform_load (No module named 'helper'; 16014)
[2022-12-20T00:19:32.017+0100] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-20T00:19:32.042+0100] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
